# Generated by Django 2.2.4 on 2019-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
